// Homepage slideshow images. Files live in the "random-works" folder.
window.RANDOM_WORKS_FOLDER = "random-works/";

window.RANDOM_WORKS = [
  "135-Cup 20 Litre XL Commercial Size Hot Elixir Dispenser.png",
  "2025 - Noodle Box 2025 Glazed ceramic embedded into concrete paving stone. Berry Street, Liverpool. Photography by Mark McNulty.jpg",
  "A Cave Door. 2025. 34 x 24 x 4 cm. Glazed stoneware ceramic, tile grout, pigment, (bracket - timber, acrylic paint, resin). Photography by Steven Devillis NY.jpg",
  "Awakening Ceremony 4.png",
  "Bate (with moody lighting) 2 .jpg",
  "Bate 08.jpg",
  "Bate dark 04.jpg",
  "Bate dark 08.jpg",
  "Bread Hands House 01.jpeg",
  "Bread Hands House 02.jpeg",
  "Break The Mould. Ikon Gallery, Birmingham 2026. Group.jpg",
  "Buddy 02.jpg",
  "Buddy 08.jpg",
  "Chris Pratt_s Torso Ascends_3_ 90 x 75cm (tbc) _ glazed ceramic, grout, pigment, timber.jpg.jpg",
  "Chris Pratt_s Torso Ascends_4_ 90 x 75cm (tbc) _ glazed ceramic, grout, pigment, timber.jpg.jpg",
  "Concerned Dogs Full Install 03.jpg",
  "Concerned Dogs Full Install 13.jpg",
  "Copy of Fitbit Worship Still 4.png",
  "Dolly Zoom, Scale Model, Seating Plan-1.jpg",
  "final.00_05_44_20.Still006.png",
  "FIRE 1,2 and 3 - this is an edit, it might look weird_.jpg",
  "Fire 6.jpg",
  "Followers (high res still 1).jpg",
  "Giant Veg Man 01.jpeg",
  "GPS_9410-Edit copy.jpg",
  "GPS_9423-Edit copy.jpg",
  "Holding Page Sreen 1_1080p.00_00_34_06.Still022.png",
  "Holding Page Sreen 1_1080p.00_01_10_07.Still002.png",
  "IMG_4499-Large copy.jpg",
  "INSULATION 05.jpg",
  "Ishiguri_s telenoid and an unrelated tomb 1.jpg",
  "Kara Chin AMV Cats, 2026 Digital animation, three screens display Hatch Gallery, Paris, 2026. © Pauline Assathiany. Courtesy of the Artists and Hatch Gallery.jpg",
  "Kara Chin, Our Father, 2026.jpg",
  "Kara Chin_Shh the Film Is Starting_LINSEED_Instllation View 1.jpg",
  "karachin.13.jpg",
  "karachin.16.jpg",
  "karachin.24.jpg",
  "karachin.7.jpg",
  "Kung Foo Skeletons. 2023. 17.5 x 10.5 x 3 cm. Glazed ceramic, grout, pigment, wood.jpg",
  "K_APL4219 Kopie.jpg",
  "Lucky 01.jpg",
  "Lucky 02.jpg",
  "Lucky 06.jpg",
  "Negative Energy Released from the Big Stone Egg. 2025. 31 x 23 x 4cm. Glazed stoneware ceramic, gold leaf, tile grout, pigment (bracket - timber, acrylic paint, resin) Photography by Steven Devillis NY .jpg",
  "Nurturing Nodes in the Nook of an Odd Sock. Gallery Miyauchi, Hiroshima 2024. Group.jpg",
  "Pasta Legs Starch Warrior 2020 - Installation View Baltic39.jpg",
  "Pity Petty Installation views by Kara Chin and Romain Sarrot, Hatch Gallery, Paris, 2026. © Pauline Assathiany. Courtesy of the Artists and Hatch Gallery. 03.jpg",
  "PSSA Kitchen Mayhem 03.jpg",
  "Quiet Table 5.jpg",
  "Rover 01.jpg",
  "Seagull Dispatch 2024. 29 x 25 x 3cm. Glazed ceramic, grout, pigment..jpg",
  "Sentient-Mecha-Furniture 2020 - Installation view 2 Baltic39.jpg",
  "SEWAGE 04.jpg",
  "SEWAGE 24.jpg",
  "ShoppingList01.jpg",
  "Sims Dream Flour shop 01.jpeg",
  "Sims Dream Flour Shop 04.jpeg",
  "start2.00_00_38_21.Still001.jpg",
  "The Goone State, 2026. Glazed stoneware ceramic. 36 x 35 x 27 cm. © Pauline Assathiany. Courtesy of the Artists and Hatch Gallery 07.jpg",
  "The Goone State, 2026. Glazed stoneware ceramic. 36 x 35 x 27 cm. © Pauline Assathiany. Courtesy of the Artists and Hatch Gallery 09.jpg",
  "The Park is Gone_5 _ 80 x 128 x 3.5 cm  _ Glazed ceramic, grout, pigment, timber.jpg",
  "Toaster Tomb(6).jpg",
  "Toaster Tomb.jpg",
  "Uneasy Over Head Wall Display 1_v2 .jpg",
  "Uneasy Over Head Wall Display 2 02.jpg",
  "Uneasy Over Head Wall Display 3 01.jpg",
  "Vogelkop in Atami. 2024. 21 x 15 x 2 cm. Glazed ceramic, grout, pigment.jpg",
  "watcing the rear view 3.jpg",
  "You take one more step and I_ll kill you, 2026 Glazed stoneware ceramic, 20 x 30.5 x 2 cm. © Pauline Assathiany. Courtesy of the Artists and Hatch Gallery.jpg"
];
